-- Esquema actual de facturas CFDI 4.0.
-- Estados canonicos usados por el servidor:
-- TIMBRADA, PENDIENTE_PAGO, CANCELADA, ERROR.

CREATE TABLE IF NOT EXISTS public.facturas
(
    id_factura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid character varying(36),
    id_emisor integer NOT NULL,
    id_cliente integer NOT NULL,
    id_contrato integer,
    serie character varying(10),
    folio character varying(20),
    fecha_emision timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_timbrado timestamp without time zone,
    tipo_comprobante character(1) DEFAULT 'I',
    lugar_expedicion character varying(5),
    moneda character varying(3) DEFAULT 'MXN',
    tipo_cambio numeric(18,6) DEFAULT 1.0,
    forma_pago character varying(2),
    metodo_pago character varying(3),
    condiciones_pago character varying(100),
    uso_cfdi character varying(4),
    subtotal numeric(18,2),
    descuento numeric(18,2) DEFAULT 0,
    total numeric(18,2),
    total_iva numeric(18,2) DEFAULT 0,
    total_isr numeric(18,2) DEFAULT 0,
    total_ret_iva numeric(18,2) DEFAULT 0,
    estado character varying(20) DEFAULT 'TIMBRADA',
    xml_path text,
    pdf_path text,
    acuse_cancelacion text,
    motivo_cancelacion character varying(2),
    uuid_relacionado character varying(36),
    tipo_relacion character varying(2),
    sello_cfdi text,
    sello_sat text,
    no_certificado character varying(20),
    no_certificado_sat character varying(20),
    nota text,
    fecha_pagado timestamp without time zone,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_usuario integer,
    total_descuento numeric(15,2) DEFAULT 0
);

ALTER TABLE IF EXISTS public.facturas
    ALTER COLUMN estado SET DEFAULT 'TIMBRADA';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'emisores'
    ) THEN
        ALTER TABLE public.facturas
            ADD CONSTRAINT facturas_id_emisor_fkey
            FOREIGN KEY (id_emisor) REFERENCES public.emisores (id_emisor);
    END IF;
EXCEPTION WHEN duplicate_object THEN
    NULL;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'clientes'
    ) THEN
        ALTER TABLE public.facturas
            ADD CONSTRAINT facturas_id_cliente_fkey
            FOREIGN KEY (id_cliente) REFERENCES public.clientes (id_cliente);
    END IF;
EXCEPTION WHEN duplicate_object THEN
    NULL;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'contratos'
    ) THEN
        ALTER TABLE public.facturas
            ADD CONSTRAINT facturas_id_contrato_fkey
            FOREIGN KEY (id_contrato) REFERENCES public.contratos (id_contrato);
    END IF;
EXCEPTION WHEN duplicate_object THEN
    NULL;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'usuarios'
    ) THEN
        ALTER TABLE public.facturas
            ADD CONSTRAINT facturas_id_usuario_fkey
            FOREIGN KEY (id_usuario) REFERENCES public.usuarios (id_usuario) ON DELETE SET NULL;
    END IF;
EXCEPTION WHEN duplicate_object THEN
    NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_facturas_uuid ON public.facturas(uuid);
CREATE INDEX IF NOT EXISTS idx_facturas_fecha ON public.facturas(fecha_emision);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON public.facturas(estado);
CREATE INDEX IF NOT EXISTS idx_facturas_cliente ON public.facturas(id_cliente);
CREATE INDEX IF NOT EXISTS idx_facturas_folio ON public.facturas(folio);
